/**
 * Emits CSS custom properties from the token objects into the web app.
 *
 *   node --experimental-strip-types src/css/generate.ts [outFile]
 *
 * Default out: ../../frontend/src/app/tokens.css (repo-relative). This is the ONE
 * place the web side gets its values, so web and mobile can never drift — both
 * read the same TS tokens. Re-run whenever tokens change.
 */
import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { semantic } from '../tokens/colors.ts';
import { scale, tracking, leading, weight } from '../tokens/typography.ts';
import { spacing, radius, layout } from '../tokens/spacing.ts';
import { easing, duration } from '../tokens/motion.ts';

const here = dirname(fileURLToPath(import.meta.url));
const outFile = process.argv[2]
  ? resolve(process.cwd(), process.argv[2])
  : resolve(here, '../../../../frontend/src/app/tokens.css');

// All vars are prefixed `--kotn-` so they never collide with Tailwind v4's own
// `@theme` namespaces (--color-*, --radius-*, --text-* …). globals.css maps the
// kotn vars into @theme to produce utilities.
const P = '--kotn';

function colorVars(mode: 'light' | 'dark'): string[] {
  const c = semantic[mode];
  return [
    `  ${P}-color-background: ${c.background};`,
    `  ${P}-color-surface: ${c.surface};`,
    `  ${P}-color-surface-elevated: ${c.surfaceElevated};`,
    `  ${P}-color-text-primary: ${c.text.primary};`,
    `  ${P}-color-text-secondary: ${c.text.secondary};`,
    `  ${P}-color-text-tertiary: ${c.text.tertiary};`,
    `  ${P}-color-text-on-accent: ${c.text.onAccent};`,
    `  ${P}-color-text-inverse: ${c.text.inverse};`,
    `  ${P}-color-border: ${c.border};`,
    `  ${P}-color-accent: ${c.accent};`,
    `  ${P}-color-success: ${c.success};`,
    `  ${P}-color-warning: ${c.warning};`,
    `  ${P}-color-danger: ${c.danger};`,
  ];
}

const staticVars: string[] = [
  // Type scale (fluid clamp)
  ...Object.entries(scale).map(([k, v]) => `  ${P}-text-${k}: ${v.fluid};`),
  // Tracking
  ...Object.entries(tracking).map(([k, v]) => `  ${P}-tracking-${k}: ${v};`),
  // Leading
  ...Object.entries(leading).map(([k, v]) => `  ${P}-leading-${k}: ${v};`),
  // Weights
  ...Object.entries(weight).map(([k, v]) => `  ${P}-weight-${k}: ${v};`),
  // Spacing (px)
  ...Object.entries(spacing).map(([k, v]) => `  ${P}-space-${k}: ${v}px;`),
  // Radius
  ...Object.entries(radius).map(([k, v]) => `  ${P}-radius-${k}: ${v}px;`),
  // Layout
  `  ${P}-layout-max-content: ${layout.maxContentWidth}px;`,
  `  ${P}-layout-measure: ${layout.readingMeasure}px;`,
  // Motion
  ...Object.entries(easing).map(([k, v]) => `  ${P}-ease-${k}: ${v.cssBezier};`),
  ...Object.entries(duration).map(([k, v]) => `  ${P}-duration-${k}: ${v}ms;`),
];

const css = `/* AUTO-GENERATED by @kotn/design-system — do not edit by hand.
   Regenerate: pnpm --filter @kotn/design-system build:css */

:root {
${colorVars('light').join('\n')}

${staticVars.join('\n')}
}

@media (prefers-color-scheme: dark) {
  :root {
${colorVars('dark').join('\n')}
  }
}

/* Manual override hook (e.g. <html data-theme="dark">) */
[data-theme='dark'] {
${colorVars('dark').join('\n')}
}
[data-theme='light'] {
${colorVars('light').join('\n')}
}
`;

writeFileSync(outFile, css, 'utf8');
console.log(`tokens.css → ${outFile}`);
